# Generated by Django 4.0.3 on 2022-03-26 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auth', '0002_emergencycontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_department', models.CharField(max_length=255)),
                ('police_department_zip_code', models.CharField(max_length=255)),
                ('occured_time', models.DateTimeField(auto_now=True)),
                ('descriptions', models.TextField()),
                ('primary_reason', models.CharField(choices=[('UC', 'Unprofessional Conduct'), ('VA', 'Verbal Abuse'), ('PA', 'Physical Assault')], max_length=255)),
                ('race_of_officer', models.CharField(choices=[('BL', 'Black/African'), ('WH', 'White/European'), ('AS', 'Asian')], max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('upload_file', models.FileField(upload_to='complaint_upload_file')),
                ('were_you_arressted', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
