# Generated by Django 4.0.3 on 2022-03-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_complaintsform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsform',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='complaint_upload_file'),
        ),
    ]
