# Generated by Django 4.0.3 on 2022-03-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_alter_complaintsform_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
